printf "Exected Appveyor environment variables\n"
printf "APPVEYOR\n"
env | grep "APPVEYOR"
printf "\n"
printf "CI\n"
env | grep "CI"
printf "\n"
printf "APPVEYOR_API_URL\n"
env | grep "APPVEYOR_API_URL"
printf "\n"
printf "APPVEYOR_PROJECT_ID\n"
env | grep "APPVEYOR_PROJECT_ID"
printf "\n"
printf "APPVEYOR_PROJECT_NAME\n"
env | grep "APPVEYOR_PROJECT_NAME"
printf "\n"
printf "APPVEYOR_PROJECT_SLUG\n"
env | grep "APPVEYOR_PROJECT_SLUG"
printf "\n"
printf "APPVEYOR_BUILD_FOLDER\n"
env | grep "APPVEYOR_BUILD_FOLDER"
printf "\n"
printf "APPVEYOR_BUILD_ID\n"
env | grep "APPVEYOR_BUILD_ID"
printf "\n"
printf "APPVEYOR_BUILD_NUMBER\n"
env | grep "APPVEYOR_BUILD_NUMBER"
printf "\n"
printf "APPVEYOR_BUILD_VERSION\n"
env | grep "APPVEYOR_BUILD_VERSION"
printf "\n"
printf "APPVEYOR_PULL_REQUEST_NUMBER\n"
env | grep "APPVEYOR_PULL_REQUEST_NUMBER"
printf "\n"
printf "APPVEYOR_PULL_REQUEST_TITLE\n"
env | grep "APPVEYOR_PULL_REQUEST_TITLE"
printf "\n"
printf "APPVEYOR_JOB_ID\n"
env | grep "APPVEYOR_JOB_ID"
printf "\n"
printf "APPVEYOR_REPO_PROVIDER\n"
env | grep "APPVEYOR_REPO_PROVIDER"
printf "\n"
printf "APPVEYOR_REPO_SCM\n"
env | grep "APPVEYOR_REPO_SCM"
printf "\n"
printf "APPVEYOR_REPO_NAME\n"
env | grep "APPVEYOR_REPO_NAME"
printf "\n"
printf "APPVEYOR_REPO_BRANCH\n"
env | grep "APPVEYOR_REPO_BRANCH"
printf "\n"
printf "APPVEYOR_REPO_COMMIT\n"
env | grep "APPVEYOR_REPO_COMMIT"
printf "\n"
printf "APPVEYOR_REPO_COMMIT_AUTHOR\n"
env | grep "APPVEYOR_REPO_COMMIT_AUTHOR"
printf "\n"
printf "APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL\n"
env | grep "APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL"
printf "\n"
printf "APPVEYOR_REPO_COMMIT_TIMESTAMP\n"
env | grep "APPVEYOR_REPO_COMMIT_TIMESTAMP"
printf "\n"
printf "APPVEYOR_REPO_COMMIT_MESSAGE\n"
env | grep "APPVEYOR_REPO_COMMIT_MESSAGE"
printf "\n"
printf "APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED\n"
env | grep "APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"
printf "\n"
printf "APPVEYOR_SCHEDULED_BUILD\n"
env | grep "APPVEYOR_SCHEDULED_BUILD"
printf "\n"
printf "PLATFORM\n"
env | grep "PLATFORM"
printf "\n"
printf "CONFIGURATION\n"
env | grep "CONFIGURATION"
exit 0




